version: "3.7"

services:
  jupyter:
    build:
      context: ./
    environment:
      - PYTHONPATH=/programming_classifierr
    command: bash -c "
      jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --no-browser --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.iopub_data_rate_limit=10000000000"
    ports:
      - "9006:8888"
    volumes:
      - ./:/programming_classifierr:delegated